---
name: Linting

on: [push, pull_request]

jobs:
  build:
    name: Run Pylint and Mypy on SgEExt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - run: |
          python -m pip install --upgrade pip
          pip install requests pylint mypy

      - run: |
          pylint sgeext.py
          mypy --install-types --non-interactive sgeext.py
