---
name: Linting

on: [push, pull_request]

jobs:
  build:
    name: Run Pylint on sgeext.py
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - run: |
          python -m pip install --upgrade pip
          pip install pylint

      - run: |
          pylint sgeext.py
